# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Corre los tests de la librería"
  lane :test do
    run_tests(
      scheme: "MyLibrary",         # Asegúrate que este scheme existe
      clean: true,
      device: "iPhone 14"
    )
  end
end